name: linksyncro
description: "A professional video downloader app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # এই দুটি লাইন অবশ্যই যুক্ত করবেন
  http: ^1.1.0
  url_launcher: ^6.2.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true